# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15cbe75e35ff0e1e0e4d6c443017a86ca442d42b64845483e8b45d4bbe255534c95dd157e1ef4aecd79291ffd484dde8ae0f7d8fb43c9c8f1c76e608f5750789

test:
  secret_key_base: b5c602134261bfd0219f72b4f3c623ad9398246890ca8ea40c3a51801238b004a5bc99d25cb85ffd62b38683a0db30ca87e63617a39f27c1374ee9c185251370

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
